/*
# Seed Knowledge Base with Trusted Health Education Content

Populates the knowledge_documents table with educational content about common health topics.
These documents are used by the AI agent's RAG system for educational queries.

## Content Categories
- Sleep health
- Heart rate / cardiovascular
- Blood pressure
- Hydration
- Nutrition
- Exercise / activity
- Mental health / stress
- General wellness

## Security
No security changes — knowledge_documents already has RLS policies allowing all authenticated users to read.
*/

INSERT INTO knowledge_documents (title, category, content, source, source_url, keywords) VALUES
('Understanding Sleep Quality', 'sleep', 'Sleep quality is determined by several factors: total duration (adults need 7-9 hours), sleep continuity (minimizing nighttime awakenings), sleep architecture (balance of deep sleep, REM, and light sleep stages), and how rested you feel upon waking. Poor sleep quality can result from stress, irregular sleep schedules, excessive screen time before bed, caffeine consumption late in the day, and underlying health conditions. To improve sleep quality: maintain a consistent sleep schedule, create a dark and cool sleeping environment, avoid screens 30-60 minutes before bed, limit caffeine after noon, and engage in relaxing activities before sleep. If sleep problems persist for more than a few weeks, consult a healthcare professional.', 'National Sleep Foundation', 'https://www.sleepfoundation.org', ARRAY['sleep','sleep quality','insomnia','rest','sleep hygiene']),

('Heart Rate Basics', 'heart_rate', 'Resting heart rate (RHR) for adults typically ranges from 60-100 beats per minute (bpm), with lower rates generally indicating better cardiovascular fitness. Athletes may have resting rates as low as 40-60 bpm. Maximum heart rate is approximately 220 minus your age. Heart rate zones for exercise: Zone 1 (50-60% of max) — light activity; Zone 2 (60-70%) — fat burning; Zone 3 (70-80%) — aerobic; Zone 4 (80-90%) — anaerobic; Zone 5 (90-100%) — maximum effort. Factors affecting heart rate include stress, caffeine, medications, temperature, body position, and emotions. A consistently elevated resting heart rate above 100 bpm (tachycardia) or below 60 bpm (bradycardia) should be discussed with a healthcare provider, especially if accompanied by dizziness, chest pain, or shortness of breath.', 'American Heart Association', 'https://www.heart.org', ARRAY['heart rate','pulse','bpm','cardiovascular','resting heart rate','tachycardia','bradycardia']),

('Understanding Blood Pressure', 'blood_pressure', 'Blood pressure is measured as two values: systolic (pressure when heart beats) over diastolic (pressure between beats). Normal blood pressure is below 120/80 mmHg. Elevated: 120-129/less than 80. Stage 1 hypertension: 130-139/80-89. Stage 2 hypertension: 140+/90+. Hypertensive crisis: 180+/120+. High blood pressure often has no symptoms, which is why regular monitoring is important. Risk factors include family history, obesity, high sodium diet, excessive alcohol, smoking, stress, and lack of physical activity. Lifestyle modifications to manage blood pressure include reducing sodium intake, regular exercise, maintaining healthy weight, limiting alcohol, managing stress, and following a heart-healthy diet like the DASH diet. If you experience severely elevated blood pressure with symptoms like severe headache, chest pain, or difficulty breathing, seek emergency care.', 'American Heart Association', 'https://www.heart.org', ARRAY['blood pressure','hypertension','systolic','diastolic','mmhg','dash diet']),

('Hydration and Health', 'hydration', 'Adequate hydration is essential for bodily functions including temperature regulation, joint lubrication, nutrient transport, and waste removal. General guidelines suggest approximately 2.7 liters per day for women and 3.7 liters for men from all beverages and foods. Individual needs vary based on activity level, climate, health conditions, and pregnancy. Signs of dehydration include thirst, dark-colored urine, fatigue, dizziness, headache, and dry mouth. Over-hydration (hyponatremia) is rare but can occur with excessive water intake during intense exercise. Tips for staying hydrated: carry a water bottle, drink water with meals, eat water-rich foods (cucumber, watermelon, soups), monitor urine color (pale yellow is ideal), and increase intake during exercise or hot weather.', 'Mayo Clinic', 'https://www.mayoclinic.org', ARRAY['hydration','water','dehydration','fluids','electrolytes']),

('Nutrition Fundamentals', 'nutrition', 'A balanced diet includes a variety of foods from all food groups. Macronutrients: carbohydrates (45-65% of daily calories) — primary energy source; proteins (10-35%) — tissue repair and muscle maintenance; fats (20-35%) — nutrient absorption and hormone production. Micronutrients include vitamins and minerals essential for various bodily functions. The USDA MyPlate model recommends: half your plate fruits and vegetables, quarter whole grains, quarter lean protein, plus dairy. Limit added sugars (less than 10% of daily calories), saturated fats (less than 10%), and sodium (less than 2300mg). Eating patterns matter: regular meals help maintain stable blood sugar, while skipping meals can lead to overeating. A Mediterranean-style diet has been associated with cardiovascular benefits. For personalized nutrition advice, consult a registered dietitian.', 'USDA Dietary Guidelines', 'https://www.dietaryguidelines.gov', ARRAY['nutrition','diet','calories','protein','carbohydrates','fat','macros','healthy eating']),

('Exercise and Physical Activity', 'exercise', 'Adults should aim for at least 150 minutes of moderate-intensity aerobic activity or 75 minutes of vigorous activity per week, plus muscle-strengthening activities on 2 or more days per week. Moderate-intensity activities include brisk walking, cycling, swimming, and gardening. Vigorous activities include running, HIIT, and fast cycling. Benefits of regular exercise include: improved cardiovascular health, weight management, stronger bones and muscles, reduced risk of chronic diseases, improved mental health and mood, better sleep quality, and increased longevity. Start slowly if new to exercise and gradually increase intensity. Include warm-ups before and cool-downs after exercise. Listen to your body — stop if you experience chest pain, severe shortness of breath, or dizziness. Combine aerobic exercise with strength training and flexibility exercises for balanced fitness.', 'CDC Physical Activity Guidelines', 'https://www.cdc.gov/physicalactivity', ARRAY['exercise','physical activity','fitness','steps','workout','aerobic','strength training']),

('Understanding SpO2 (Blood Oxygen)', 'vitals', 'SpO2 (peripheral capillary oxygen saturation) measures the percentage of hemoglobin saturated with oxygen. Normal SpO2 for healthy individuals at sea level is 95-100%. Values below 90% (hypoxemia) may indicate a need for medical evaluation. SpO2 can be measured with pulse oximeters, which are non-invasive devices placed on the finger. Factors affecting SpO2 readings include: altitude, respiratory conditions (asthma, COPD, pneumonia), circulatory issues, anemia, smoking, and skin pigmentation. If you consistently see SpO2 readings below 92%, or if low readings are accompanied by shortness of breath, chest pain, confusion, or blue-tinged lips/fingers, seek medical attention promptly. Pulse oximeters can be less accurate with dark nail polish, cold fingers, or poor circulation.', 'Mayo Clinic', 'https://www.mayoclinic.org', ARRAY['spo2','blood oxygen','oxygen saturation','pulse oximeter','hypoxemia']),

('Stress and Mental Health', 'mental_health', 'Chronic stress can have significant impacts on physical health, including elevated blood pressure, weakened immune function, digestive problems, sleep disturbances, and increased risk of cardiovascular disease. Common stress management techniques include: regular physical exercise, mindfulness meditation, deep breathing exercises (such as 4-7-8 breathing), progressive muscle relaxation, adequate sleep, social connection, and limiting caffeine and alcohol. Warning signs that stress may be overwhelming include: persistent anxiety or depression, difficulty functioning in daily activities, substance use changes, sleep problems lasting more than a few weeks, and physical symptoms like chest pain or severe headaches. Mental health is as important as physical health. If you are experiencing persistent feelings of sadness, anxiety, or thoughts of self-harm, please reach out to a mental health professional or contact a crisis helpline. You are not alone, and help is available.', 'National Institute of Mental Health', 'https://www.nimh.nih.gov', ARRAY['stress','mental health','anxiety','depression','mindfulness','meditation','wellness']),

('Understanding Body Weight and BMI', 'body', 'Body Mass Index (BMI) is a screening tool that uses height and weight to estimate body fat. BMI categories: Underweight (below 18.5), Normal (18.5-24.9), Overweight (25-29.9), Obese (30+). BMI has limitations — it does not distinguish between muscle and fat mass, and may not be accurate for athletes, elderly, or pregnant individuals. However, it remains a useful screening tool. Healthy weight management involves sustainable lifestyle changes rather than crash diets: balanced nutrition, regular physical activity, adequate sleep, stress management, and gradual changes. Weight fluctuations of 1-2 kg per day are normal due to fluid changes. For sustainable weight loss, aim for 0.5-1 kg per week. Consult a healthcare provider before starting any weight loss program, especially if you have underlying health conditions.', 'CDC', 'https://www.cdc.gov/healthyweight', ARRAY['weight','bmi','body mass index','obesity','weight management','body composition']),

('Blood Glucose Monitoring', 'vitals', 'Blood glucose (blood sugar) levels indicate how well your body manages glucose. For non-diabetic adults: fasting blood glucose should be 70-99 mg/dL, and below 140 mg/dL two hours after eating. For people with diabetes, target ranges may differ — follow your healthcare providers recommendations. Hypoglycemia (low blood sugar, below 70 mg/dL) can cause shakiness, sweating, confusion, and in severe cases, loss of consciousness. Treat with fast-acting carbohydrates (glucose tablets, juice). Hyperglycemia (high blood sugar) can cause increased thirst, frequent urination, fatigue, and blurred vision. Factors affecting blood glucose include diet, physical activity, stress, illness, medications, and sleep quality. If you experience persistent high or low blood sugar readings, or symptoms of diabetic ketoacidosis (fruity breath, nausea, deep breathing, confusion), seek immediate medical attention.', 'American Diabetes Association', 'https://www.diabetes.org', ARRAY['blood glucose','blood sugar','diabetes','hypoglycemia','hyperglycemia','glucose'])
ON CONFLICT DO NOTHING;